### ISSUE TITLE
CIHR not working in TEAMMATES

### ISSUE THREAD

**Issue by xpdavid** [pyokagan/CanIHasReview#34]
Try to generate CIHR for https://github.com/TEAMMATES/teammates/pull/6797

Click start new iteration several times https://canihasreview.herokuapp.com/TEAMMATES/teammates/pull/6797

**Comment by pyokagan** [comment]
Unfortunately the logs for that PR are gone since Heroku has a 1,500 line limit :-/ Even if I did have the logs, CIHR didn't have enough logging for me to diagnose the issue.

Thankfully, the *rewritten* CIHR is not hosted on heroku (no log size limit!) and has proper logging. So, even though this specific issue can't be solved, if any similar issue occurs in the future I'll be able to fix it.
