### ISSUE TITLE
Error for Job ID: job-098843e4-3a6f-45ea-b31a-c2b6014eb7d7

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [pyokagan/CanIHasReview#37]
I tried submitting an iteration for a [PR in addressbook-level3](https://github.com/se-edu/addressbook-level3/pull/128) a few times. However, all my attempts thus far have resulted in the below error message:
![Screenshot (147)](https://user-images.githubusercontent.com/69678785/160334606-e4379780-c4ef-489b-9675-96367cf11224.png)

**Comment by pyokagan** [comment]
Logs showing what is causing the error:

```
To https://github.com/se-edu/addressbook-level3.git
 * [new branch]        refs/pr/129/2/base -> refs/pr/129/2/base
 ! [remote rejected]   refs/pr/129/2/head -> refs/pr/129/2/head (refusing to allow a GitHub App to create or update workflow `.github/workflows/gradle.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/se-edu/addressbook-level3.git'
```

Seems like GitHub is being overly-restrictive since we are just pushing refs, not branches or tags, but oh well.

@damithc I've added the "workflows" permission to the CIHR app. GitHub should have sent you an email requesting that added permission. You'll need to accept it, and then the problem should be resolved.

**Comment by damithc** [comment]
> @damithc I've added the "workflows" permission to the CIHR app. GitHub should have sent you an email requesting that added permission. You'll need to accept it, and then the problem should be resolved.

Did that just now. Thanks very much for the quick help @pyokagan

**Comment by pyokagan** [comment]
Seems like it works :-)
